# yaml-language-server: $schema=../schema.json

name: hello-world
jobs:
  echo:
    steps:
      # simple example uses bash to echo "hello world" to
      # standard output
      - run: echo "Hello, World!"
        description: "Prints 'Hello, World!' to stdout."

      # We can do the same thing with the "echo" action
      # You an check out the echo action in ../actions/echo.ts
      - action: "echo"
        description: "Prints 'Hello, World!' to stdout."
        input:
          content: "Hello, World!"
  expressions:
    steps:
      - action: "echo"
        input:
          content: ${{ step.name }}
      - action: "echo"
        input:
          content: ${{ "awesome".toUpperCase() }}
  output:
    steps:
      - name: whoami
        run: echo "name=Mr. Awesome" >> $ELWOOD_OUTPUT
      - action: echo
        input:
          content: ${{ steps.whoami.outputs.name }}
