name: Release CLI

on: workflow_dispatch

jobs:
  cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - run: deno check src/**/*.ts actions/**/*.ts
      - name: build
        run: deno task build-cli >> $GITHUB_OUTPUT

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: false
          make_latest: true
          files: ./dist/*
          tag_name: v${{ steps.build.outputs.new_version }}
